export const SELECT_HERO = 'SELECT_HERO'

//GAMESTATE AI
export const JACK_EN_POY_AI = 'JACK_EN_POY_AI'
export const SET_HERO_AI = "SET_HERO_AI"
export const UPDATE_DEBUFF_AI = "UPDATE_DEBUFF_AI"
export const REMOVE_DEBUFF_AI = "REMOVE_DEBUFF_AI"

//GAMESTATE PLAYER

export const JACK_EN_POY_PLAYER = 'JACK_EN_POY_PLAYER'
export const SET_HERO_PLAYER = "SET_HERO_PLAYER"
export const SKILL_AI = "SKILL_AI"
export const SKILL_SELF = "SKILL_SELF"
export const ATTACK_AI = "ATTACK_AI"
export const RESET_CHANCE_PLAYER = "RESET_CHANCE_PLAYER"
export const DEBUFFING_AI = "DEBUFFING_AI"